"use client";

import { useEffect, useState } from "react";
import type { ResearchReviewSummary, ReviewAnalysis } from "@/lib/intelligence/types";
import type { Branch } from "@/types/database";
import { ActionFeedback, type FeedbackTone } from "@/components/action-feedback";

async function request<T = ReviewAnalysis>(body: Record<string, unknown>): Promise<T> {
  const response = await fetch("/api/research-intelligence", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Research intelligence request failed."); return result as T;
}

export function ResearchIntelligencePanel({ workspaceId, branches, selectedBranchId, mode, onContinueToMerge }: { workspaceId: string; branches: Branch[]; selectedBranchId: string | null; mode: "reviews" | "ci"; onContinueToMerge: (sourceBranchId: string, targetBranchId: string, reviewId: string) => void }) {
  const [source, setSource] = useState(""); const [target, setTarget] = useState(""); const [analysis, setAnalysis] = useState<ReviewAnalysis | null>(null);
  const [reviews, setReviews] = useState<ResearchReviewSummary[]>([]); const [reason, setReason] = useState(""); const [reasonFeedback, setReasonFeedback] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<{ tone: FeedbackTone; title: string; detail?: string; next?: string } | null>(null);
  const [savingReason, setSavingReason] = useState(false);
  useEffect(() => { void fetch(`/api/research-intelligence?workspaceId=${workspaceId}`).then(async (response) => { if (response.ok) setReviews(await response.json() as ResearchReviewSummary[]); }); }, [workspaceId]);
  const selectedBranch = branches.find((branch) => branch.id === selectedBranchId);
  const effectiveSource = source || (selectedBranch?.name !== "main" ? selectedBranch?.id : undefined) || branches.find((branch) => branch.name !== "main")?.id || branches[0]?.id || "";
  const effectiveTarget = target || branches.find((branch) => branch.name === "main")?.id || branches[0]?.id || "";
  async function run(action: "analyze" | "create-review") { setBusy(true); setError(null); setFeedback(null); try { const result = await request({ action, workspaceId, sourceBranchId: effectiveSource, targetBranchId: effectiveTarget }); setAnalysis(result); setFeedback({ tone: "success", title: "Research Review created", detail: `${result.sourceBranchName} → ${result.targetBranchName} · ${result.checks.length} Research CI checks completed.`, next: "Inspect warnings, save an optional decision reason, then prepare the merge." }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Analysis failed."); } finally { setBusy(false); } }
  async function rerunCi() { const review = reviews.find((item) => item.source_branch_id === effectiveSource && item.target_branch_id === effectiveTarget && item.status === "open" && !item.stale); if (!review) { setError("Create a Research Review first."); return; } setBusy(true); setError(null); setFeedback(null); try { const result = await request({ action: "rerun-ci", reviewId: review.id }); setAnalysis(result); const passed = result.checks.filter((check) => check.status === "pass").length; const warnings = result.checks.filter((check) => check.status === "warning").length; const blocking = result.checks.filter((check) => check.status === "fail").length; setFeedback({ tone: blocking ? "warning" : "success", title: "Research CI complete", detail: `${result.checks.length} checks · ${passed} passed · ${warnings} warnings · ${blocking} blocking.`, next: "Review warnings before preparing the merge." }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Research CI failed."); } finally { setBusy(false); } }
  async function openReview(review: ResearchReviewSummary) { setBusy(true); setError(null); setReasonFeedback(null); try { const loaded = await request({ action: "load-review", reviewId: review.id }); setAnalysis(loaded); setReason(loaded.resolutionReason ?? ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load review."); } finally { setBusy(false); } }
  async function saveReason() { if (!analysis?.reviewId) return; setBusy(true); setSavingReason(true); setError(null); setReasonFeedback(null); try { const saved = await request<{ ok: true; resolutionReason: string | null }>({ action: "record-reason", reviewId: analysis.reviewId, reason }); setReason(saved.resolutionReason ?? ""); setAnalysis((current) => current ? { ...current, resolutionReason: saved.resolutionReason } : current); setReasonFeedback("Reason saved"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save reason."); } finally { setBusy(false); setSavingReason(false); } }

  return <section className="mx-auto max-w-6xl">
    {feedback && <div className="mb-4"><ActionFeedback {...feedback} /></div>}
    {reasonFeedback && <p className="mb-4 rounded border border-emerald-500/30 bg-emerald-500/8 p-3 text-sm text-emerald-300">✓ {reasonFeedback}</p>}
      <div className="mb-4 flex flex-col gap-4 border-b border-[#30363d] pb-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-base font-semibold">{mode === "reviews" ? "Research Reviews" : "Research CI"}</h2><p className="mt-1 text-sm text-[#8b949e]">{mode === "reviews" ? "Review branch changes before they enter main." : "Deterministic checks with advisory research warnings."}</p></div><div className="flex flex-wrap items-end gap-2"><BranchSelect label="Source" value={effectiveSource} setValue={(value) => { setSource(value); setAnalysis(null); setFeedback(null); }} branches={branches} /><span className="pb-1.5 text-zinc-600">→</span><BranchSelect label="Target" value={effectiveTarget} setValue={(value) => { setTarget(value); setAnalysis(null); setFeedback(null); }} branches={branches} /><button disabled={busy || !effectiveSource || !effectiveTarget || effectiveSource === effectiveTarget} onClick={() => void (mode === "reviews" ? run("create-review") : rerunCi())} className="h-8 rounded-md bg-[#1f6feb] px-3 text-sm font-medium text-white hover:bg-[#388bfd] disabled:opacity-50">{busy ? mode === "reviews" ? "Creating Research Review…" : "Running 6 research integrity checks…" : mode === "reviews" ? "New Research Review" : "Rerun Research CI"}</button></div></div>
    {error && <p className="mb-4 rounded border border-red-500/30 bg-red-500/8 p-3 text-sm text-red-300">{error}</p>}
    {!analysis ? reviews.length ? <div className="overflow-hidden rounded-md border border-[#30363d] bg-[#0d1117]"><div className="border-b border-[#30363d] bg-[#161b22] px-4 py-2 text-sm font-medium">{reviews.length} research review{reviews.length === 1 ? "" : "s"}</div>{reviews.map((review) => <button key={review.id} disabled={busy || review.stale || review.status !== "open"} onClick={() => void openReview(review)} className="grid w-full gap-2 border-b border-[#21262d] px-4 py-3 text-left text-xs last:border-0 hover:bg-[#161b22] disabled:cursor-default disabled:opacity-70 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="text-sm font-semibold"><span className="text-[#58a6ff]">{review.sourceBranchName}</span> → {review.targetBranchName}</p><p className="mt-1 text-[#8b949e]"><span className={review.status === "open" ? "font-medium text-emerald-400" : ""}>{review.status}</span> · CI {review.ciStatus ?? "not run"} · heads <code>{review.source_commit_id.slice(0, 7)}</code> / <code>{review.target_commit_id.slice(0, 7)}</code> · {new Date(review.created_at).toLocaleString()}</p>{review.stale && <p className="mt-2 font-medium text-amber-300">Research Review is out of date. Rerun it for the current heads.</p>}</div><span className="text-xs font-medium text-[#58a6ff]">{review.stale || review.status !== "open" ? "" : "Open review →"}</span></button>)}</div> : <div className="rounded-md border border-dashed border-[#30363d] px-6 py-6 text-center"><p className="text-sm text-[#8b949e]">No research reviews yet.</p></div> : <>
      <div className="mb-4 rounded-md border border-[#30363d] bg-[#161b22] px-4 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-base font-semibold"><span className="text-[#58a6ff]">{analysis.sourceBranchName}</span> → {analysis.targetBranchName}</p><span className={`text-sm font-medium ${analysis.mergeHasConflicts ? "text-red-300" : analysis.status === "warning" ? "text-amber-300" : "text-emerald-300"}`}>{analysis.mergeHasConflicts ? "Conflict" : analysis.status === "warning" ? "Open · CI warnings" : "Open · CI passing"}</span></div><p className="mt-2 font-mono text-xs text-zinc-500">{analysis.sourceHeadId.slice(0, 7)} → {analysis.targetHeadId.slice(0, 7)}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-zinc-500"><span>{analysis.commitsChanged} commits</span><span>{analysis.artifactsChanged} artifacts</span><span>{analysis.knowledgeChanges.length} knowledge changes</span><span>{analysis.knowledgeChanges.filter((item) => item.category === "numerical").length} numerical</span></div></div>
      <Panel title="Knowledge Changes"><div className="divide-y divide-white/8">{analysis.knowledgeChanges.map((change, index) => <div key={`${change.artifactId}:${index}`} className="py-3 text-xs"><p><span className={change.category === "removed" ? "text-red-300" : change.category === "numerical" ? "text-amber-300" : "text-emerald-300"}>{change.category === "introduced" ? "+" : change.category === "removed" ? "−" : change.category === "numerical" ? "!" : "~"} {change.category}</span><span className="ml-2 text-zinc-600">{change.artifactName}</span></p>{change.before && <p className="mt-2 text-red-200/70">Before: {change.before}</p>}{change.after && <p className="mt-1 text-emerald-200/70">After: {change.after}</p>}</div>)}{!analysis.knowledgeChanges.length && <p className="py-4 text-sm text-zinc-600">No extracted claim changes.</p>}</div></Panel>
      <Panel title="Research CI"><div className="divide-y divide-white/8">{analysis.checks.map((check) => <details key={check.checkType} className="group py-3"><summary className="cursor-pointer list-none text-sm font-medium"><span className={check.status === "pass" ? "text-emerald-400" : check.status === "fail" ? "text-red-400" : "text-amber-400"}>{check.status === "pass" ? "✓" : check.status === "fail" ? "✕" : "⚠"}</span><span className="ml-2">{check.title}</span></summary><p className="mt-2 pl-6 text-xs leading-5 text-zinc-500">{check.details}</p><pre className="mt-2 max-h-52 overflow-auto whitespace-pre-wrap pl-6 text-xs text-zinc-600">{JSON.stringify(check.metadata, null, 2)}</pre></details>)}</div></Panel>
      <Panel title="Evidence / Provenance"><div className="space-y-3">{analysis.claims.map((claim) => <div key={claim.id} className="text-xs"><p className="text-zinc-300">{claim.text}</p><p className="mt-1 text-zinc-600">{claim.artifactName} · version {claim.artifactVersionId.slice(0, 8)}</p><p className="mt-1 text-zinc-500">{claim.evidence ? `Evidence: ${claim.evidence.text}` : "No adequate independent evidence match found."}</p></div>)}</div></Panel>
      <Panel title="Potential Impact"><div className="space-y-4">{analysis.blastRadius.map((item) => <div key={item.sourceClaim} className="font-mono text-xs"><p>{item.sourceClaim}</p>{item.direct.map((claim) => <p key={claim} className="ml-5 mt-2 text-amber-300">↓ direct · {claim}</p>)}{item.downstream.map((claim) => <p key={claim} className="ml-10 mt-2 text-zinc-500">↓ downstream · {claim}</p>)}</div>)}{!analysis.blastRadius.length && <p className="text-sm text-zinc-600">No stored downstream claim relationships are affected.</p>}</div></Panel>
      {mode === "reviews" && <Panel title="Merge"><p className="text-sm text-zinc-400">AI and heuristics surface risks. The researcher decides. Advisory warnings do not block merge; deterministic textual conflicts still require the existing resolution flow.</p>{analysis.reviewId && <div className="mt-4 flex gap-2"><input value={reason} onChange={(event) => { setReason(event.target.value); setReasonFeedback(null); }} placeholder="Why are you accepting these research changes? (optional)" className="min-w-0 flex-1 rounded border border-white/10 bg-[#0d0f12] px-3 py-2 text-xs" /><button disabled={busy} onClick={() => void saveReason()} className="rounded border border-white/10 px-3 text-xs disabled:opacity-50">{savingReason ? "Saving…" : "Save reason"}</button></div>}<div className="mt-4 space-y-1 text-xs text-emerald-300"><p>✓ Review current</p><p>✓ Research CI complete</p><p>✓ Textual checks ready</p></div><button disabled={!analysis.reviewId || busy} onClick={() => analysis.reviewId && onContinueToMerge(analysis.sourceBranchId, analysis.targetBranchId, analysis.reviewId)} className={`mt-4 rounded-md px-4 py-2 text-xs font-semibold text-white disabled:opacity-50 ${analysis.mergeHasConflicts ? "bg-red-700 hover:bg-red-600" : "bg-[#238636] hover:bg-[#2ea043]"}`}>{analysis.mergeHasConflicts ? "Resolve textual conflicts" : "Merge Research Review"}</button></Panel>}
    </>}
  </section>;
}

function BranchSelect({ label, value, setValue, branches }: { label: string; value: string; setValue: (value: string) => void; branches: Branch[] }) { return <label className="grid gap-1 text-xs text-[#8b949e]">{label}<select value={value} onChange={(event) => setValue(event.target.value)} className="h-8 rounded-md border border-[#30363d] bg-[#21262d] px-2 font-mono text-xs text-zinc-300">{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-4 rounded-md border border-[#30363d] bg-[#0d1117]"><h3 className="border-b border-[#30363d] bg-[#161b22] px-4 py-2 text-base font-semibold">{title}</h3><div className="p-4">{children}</div></section>; }
